#
# ubuntu_python dockerfile
#

FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y python
RUN apt-get install -y python-dev
RUN apt-get install -y python-pip
RUN apt-get install -y python-virtualenv
RUN mkdir /content